version: '3.8'

services:

  app1:
    build: ./csharp_app
    env_file:
      - .env
    depends_on:
      - app2
    networks:
      - appnet
    ports:
      - "${APP1_PORT}:${APP1_PORT}"  

  app2:
    build: ./cpp_app
    env_file:
      - .env
    networks:
      - appnet
    ports:
      - "${APP2_PORT}:${APP2_PORT}"  

networks:
  appnet:
    driver: nat  # Windows container modunda 'nat', Linux'ta 'bridge'
