version: '3.8'

services:
  app1:
    build: ./csharp_app
    environment:
      - APP2_HOST=${APP2_HOST}
      - APP2_PORT=${APP2_PORT}
    networks:
      - appnet
    ports:
      - "${APP1_PORT}:${APP1_PORT}"  
  app2:
    build: ./cpp_app
    environment:
      - APP_MAIN_HOST=${APP_MAIN_HOST}
      - APP_MAIN_PORT=${APP_MAIN_PORT}
    networks:
      - appnet
    ports:
      - "${APP2_PORT}:${APP2_PORT}"  

networks:
  appnet:
    driver: nat  # Windows container modunda 'nat', Linux'ta 'bridge'
